
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: never
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  thymeleaf:
    cache: false
  thymeleaf3:
    decoupled-logic: true
server:
  port: 8181
  error:
    whitelabel:
      enabled: false

logging.level:
  org.hibernate.SQL: debug
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder : trace
    springframework:
      web.servlet : debug
cloud:
  aws:
    s3:
      bucket: image-test-suyoung
      dir: threads-challenge
    region:
      static: ap-northeast-2
    stack:
      auto: false